### ISSUE TITLE
Using .set() when there is more than one outcome

### ISSUE THREAD

**Issue by omencat** [rchipka/node-osmosis#106]
I have a use case where there is either a span element or an image (alt text) element. I can get osmosis to capture either one or the other. I would like to add some logic to determine which is present, and then capture the text. Any tips?

```
.find(...)
.set({
  // if img is present use the text in alt, else use the text in span
  'CompanyName': 'span.companyName' || 'img@alt'
})
```

**Comment by rchipka** [comment]
You can use the CSS `,` operator:

` { CompanyName: "span.companyName, img@alt" }`

**Comment by omencat** [comment]
Works like a charm!
