### ISSUE TITLE
Modifying selector-results before following

### ISSUE THREAD

**Issue by z3to** [rchipka/node-osmosis#111]
Great library! Thank you so much for your work!

It might be that I’m missing something, but I couldn’t find a way to change the url that is being created by the selector within the follow-function before it is being followed. In my case I get for example the following href:

`http://www.host.tld/path/page`

And I would like to change that to:

`http://www.host.tld/path/page_extended`

Is there any way to do that?

**Comment by rchipka** [comment]
You can use `.find(selector).get(function (context, data))` where the callback function returns either a Node or a URL string. Let me know if you have any other questions.
