### ISSUE TITLE
Can't get submit() to work (absolute form action path)

### ISSUE THREAD

**Issue by patrickjane** [rchipka/node-osmosis#112]
Not sure if im using it wrong or maybe it is some missing feature, but the submit() command seems to be unable to build a complete URL out of the form's action. Instead, it trys to post to the form's action alone, which in my case is some relative path ('/some/script.php5').

Basically I only have 2 commands:

```
    osmosis
    .get(url)
    .submit(selector, params)
    .log(console.log)
    .error(console.log)
    .debug(console.log);
```

I can verfiy that the selector actually works, but for the submit part this is what I will get as log output:

```
(get) loaded [get] https://www.domain.tld
(get) getaddrinfo ENOTFOUND some some:443, retrying https://some/script.php5? (1/3) 
(get) getaddrinfo ENOTFOUND some some:443, retrying https://some/script.php5? (2/3) 
(get) getaddrinfo ENOTFOUND some some:443, retrying https://some/script.php5? (3/3) 
(submit) [post] https://some/script.php5? - getaddrinfo ENOTFOUND some some:443
```

As you can see, instead of posting to https://www.domain.tld/some/script.php it tries to post to https://some/scipt.php.

Am I missing some command in between?

[edit]
I'm trying to work around this somehow, and I found that `return document.location.resolve(node.getAttribute('action'));` in `form.getAction` is causing the issue. It actually resolves to `https://some/script.php5`. 
When I manually call
`document.location.resolve('some/script.php5');` (note the missing leading /)
it will in fact return `https://www.domain.tld/some/script.php5`.

Since the actual HTML form action is in fact having a value of '/some/script.php5' (WITH leading /), I assume that the resolve-function cannot resolve absolute form-action paths starting with '/'. I am by no means expert in anything I said, and I am having quite a hard time analyzing this, but would this be the desired behaviour? I don't know what kind of function the `resolve` one is, so I cannot look up a function description (I am also no javascript expert).

To be honest, I really would like to use osmosis, it seams like a neat library which would do exactly what I want. But I am really having a hard time figuring out how it works, since the documentation/examples at least for me is not really self-explanatory. 

[edit2]

Digging even more into the code, I found that the root cause is that in `form.getAction`the  `node.getAttribute('action')` is returning `//some/script.php5` instead of `/some/script.php5`. If I get it right, the resolve-function is node URL's resolve function supplied with the documents url, which in turn is the parsed URL from the request.
My tests with minimal example code indicated that node URL's resolve function will behave exactly as I noticed with osmosis, that is: 
`URL.resolve(URL.parse('https://www.domain.tld/'), '//some/script.php5') // -> https://some/script.php5`

`URL.resolve(URL.parse('https://www.domain.tld/'), '/some/script.php5')  // -> https://www.domain.tld/some/script.php5`

Summary:
- The `submit` command uses the `getAction` function to find out the URL to POST to
- `getAction` in turn uses `document.location.resolve` (^= `URL.resolve`), but the supplied parameter contains an additional second leading slash, although in the HTML the attribute value in fact contains only **one leading slash** (`<form action="/some/script.php5" method="POST" id="some-id">`)
- this will lead to URL.resolve beeing unable to produce the correct full URL, and thus the `submit` will fail

I can't be bothered to check even further why the action-parameter will be '//some/script.php5', so my quick-and-dirty fix making it work looks like this:

form-functions.js

```
form.getAction = function (node) {
    var document = node.doc();

    if (node.hasAttribute('action')) {
        return document.location.resolve(node.getAttribute('action')).replace('//', '/');   // replace and double-slashes with single slashes
    } else if (node.hasAttribute('formaction')) {
        return document.location.resolve(node.getAttribute('formaction'));
    } else {
        return document.location.href;
    }
};
```

[edit3]
After more experiments with my code, it turned out that the URL I initially passed to .get() indeed and accidentially contained a double slash. While the .get() worked, this in fact lead to the HTML containting a `<form action="//...">`. So it seems like the HTML was generated by the php website depending on what URL I call, thus resulting in node/osmosis incompatible paths.

I actually fixed this now by initially calling a valid URL in .get() without any double-slashes, so the submit() works without the dirty "fix" above :)

This issue could probably be considered as invalid then/can be closed.

**Comment by rchipka** [comment]
Glad you were able to sort it out!
