### ISSUE TITLE
how to make find optional

### ISSUE THREAD

**Issue by Freundschaft** [rchipka/node-osmosis#114]
if I use find to look for an entry, the whole osmosis request stops if the element cannot be found, how can I make a find optional?

**Comment by rchipka** [comment]
You can use [.do()](https://rchipka.github.io/node-osmosis/Command.html#do__anchor).

> Execute each argument asynchronously using the current context and data. After each argument has finished, Command.do will continue to the immediately following command using the original context. 

```javascript
osmosis
    ...
    .do(
        osmosis.find('might-exist')
               .set(...)
      )
    ...
```

**Comment by Freundschaft** [comment]
cool, thanks!

**Comment by oshliaer** [comment]
Goodly!
