### ISSUE TITLE
Cant find tbody

### ISSUE THREAD

**Issue by NegativeIQ** [rchipka/node-osmosis#118]
Im trying to scrap from a simple table and i ran into a problem with tbody.
For what i want to scrap inspect element in chrome reports: 
`html body div#content div#main-content table#searchResult tbody tr`
Above `tbody` (inside table) is `thead` with two `tr` elements i dont need.

```
var osmosis = require('osmosis');

osmosis
.get('http://localhost/test/index.html')
.find('#searchResult')
.find('tbody')
.find('tr')
.set({
	'title': 'div.Name > a.Link',
	'img': 'img'
})
.data(function(infodata) {
    console.log(infodata.title);
    console.log(infodata.img + '\n');
})
.log(console.log)
.error(console.log)
.debug(console.log)
```
```
(find) found 1 results for "#searchResult"
(find) no results for "tbody"
```
As you can see it should work. But it fails at tbody, and moving tbody after or before elements and using space or `<` `>` does not fix a problem. 

Please note if i remove `tbody` completely from find and set functions it works fine. Only it also adds two undefined elements from `thead`. I can skip them its not a problem, but these looks like bug and im reporting it. Webpage is on localhost and its a simple copy from site i want to scrap, served by WAMP server. No other modules are used, just clean .js file and it only requires osmosis. I think i gave every detail i could, if you need anything else just ask.

**Comment by rchipka** [comment]
Can you verify that tbody is actually in the raw source code? The reason I ask is because if the source is viewed using a browser's DOM Inspector it will usually inject nodes like `tbody` and `thead` even if they aren't in the original source code.

**Comment by NegativeIQ** [comment]
Yes it is present in html source code. Both tbody and thead.

**Comment by rchipka** [comment]
I'm unable to reproduce the issue. Would you be able to post the relevant bit of HTML code?

**Comment by NegativeIQ** [comment]
After PC reinstall along with everything on it (including node), problem is gone. So my only guess, its ether i missed something (most likely), node version or some other module (but its unlikely since i only required osmosis while developing scrapper). Anyway i will close ticket since problem (probably my own mistake) is magically resolved.
