### ISSUE TITLE
get each with set

### ISSUE THREAD

**Issue by 3zzy** [rchipka/node-osmosis#121]
Hi,

```
.get(url)
.find('#ListView')
.set({
  'title': '.title a',
  'price': '.price',
  'shipping': '.shipping',
  'extras': '.extras'
})
.data(function(listing) {
  console.log(listing);
})
.done(function(){
  console.log('Done.');
})
```

works great, but it only gets the first match, how do I get all the listings on the page?

**Comment by krtooch** [comment]
hello.

Maybe in your .find() you should specify a class(.) or more general selector, instead of an id(#), wich is normaly unique. it's normal it find only 1 item if you psecified id)

**Comment by rchipka** [comment]
@krtooch Correct!
