### ISSUE TITLE
Scrape as HTML ?

### ISSUE THREAD

**Issue by yopbeast** [rchipka/node-osmosis#128]
Hi, this is such an awesome scraper.

I would like to ask, how do i retrieve the untouched html element ?

I tried this without any luck :

``` javascript

.find('#table')
.set({
 'htmlTABLE': '@html'
})
```

any help please?

**Comment by rchipka** [comment]
You can use the `:html` pseudo selector to select the inner HTML and the `:source` pseudo selector to select the outer HTML.

**Comment by eashish93** [comment]
`:html` selector doesn't work. It throws the error: 
*str is not defined* from ../node_modules/css2xpath/index.js:323

**Comment by francescozaia** [comment]
I can confirm @eashish93 comment, gave a quick look at the problem and it can be verified also [here](https://css2xpath.github.io/) by putting any selector followed by `:html` pseudo.

**Comment by muhajirdev** [comment]
what's the progress on this?

**Comment by dannyongtey** [comment]
Try adding a space after the `:html` pseudo. Eg.
```
osmosis
.get(url)
.find('a')
.set({ item: ' :html' })
```
