### ISSUE TITLE
:not selector

### ISSUE THREAD

**Issue by joefraley** [rchipka/node-osmosis#131]
It looks like the `:not()` selector doesn't work. for example, with HTML of this structure:

```html
<div class="status-date">
      <strong>Date Available:</strong><span>10/05/2016</span>
</div>
``` 

I'd expect to be able to select:
`.status-date > *:not(strong)`

But the debugger throws the following error:

```bash
XPath error : Invalid expression
.//*[contains(concat(" ",normalize-space(@class)," ")," status-date ")] *[not(strong)]
                                                                         ^
xmlXPathEval: evaluation failed
```

**Comment by rchipka** [comment]
For now, you can simply remove the `*` from the selector.

I'm transferring this issue to [css2xpath](https://github.com/css2xpath/css2xpath).

Check out [css2xpath.github.io](https://css2xpath.github.io/) if you'd like to experiment with Osmosis CSS selectors and CSS selector extensions.
