### ISSUE TITLE
shouldn't be a way for setting base path in follow command? 

### ISSUE THREAD

**Issue by ImanMh** [rchipka/node-osmosis#134]
I would like to set base path in follow command like this: 
```javascript
osmosis
.get('http://domain.com/test')
.follow('http://domain.com/short-links' ,'meta[itemprop=productID]@content')
```
The scenario is clear.

**Comment by rchipka** [comment]
You could use the XPath `starts-with()` or the `:path(...)` CSS extension.

```javascript
.follow("meta[itemprop=productID][starts-with(@href, 'http://domain.com/short-links')]@content")
```

or

```javascript
.follow("meta[itemprop=productID]:internal:path('/short-links')@content")
```

The `:internal` pseudo-class specifies local links. There's also `:external` and `:domain(..)`.

**Comment by ImanMh** [comment]
@rchipka is this going to set my base path or is it going to filter the results to links that start with a specific base path? I don't want to filter my results. The links I'm looking for are ```meta[itemprop=productID]@content``` but the problem is that the content attribute contain a part of the url that I want osmosis to follow. This is why I want to set the base path to something else. 
Are we in the same page?

**Comment by rchipka** [comment]
@ImanMh Osmosis _should_ resolve the followed links based on the current page URL. If not, then this is a bug. If you need to resolve the URLs to anything other than the current base URL, then your best option for now is to use `.then` and rewrite the links manually.

**Comment by rchipka** [comment]
Alternatively, you could do something like this:

```javascript
osmosis
.find('meta[itemprop=productID]')
.get(function (context) {
  return 'http://domain.com/short-links' + context.getAttribute('content');
})
...
```

**Comment by ImanMh** [comment]
That can solve the issue
