### ISSUE TITLE
Set form data without sending the form

### ISSUE THREAD

**Issue by vgesteljasper** [rchipka/node-osmosis#144]
Is there a way to fill in some form data without sending the form,
and instead use .click on the submit button?

**Comment by yortrosal** [comment]
Have you solved it? I haven't personally done it though but I believe it can be done. Can you share some details of what you're trying to solve?

**Comment by vgesteljasper** [comment]
I haven't been able to solve it yet.

I'm trying to log in to a webpage to later display some personal stats in the terminal via blessed.
The login form on that page though cannot be submitted in a regular fashion but needs to be submitted with a press on a button (which does some javascript on their end) to login.

That's why I am trying to fill in the credentials first and perform a click on the submit button.

**Comment by yortrosal** [comment]
I see. did the `.login('username', 'password')` didn't work for you? 

If it doesn't, Have you tried using something like this?
```
osmosis
 .get('URL')
 .submit('username field selector', 'username data') 
 .submit('password field selector','password')
 .click('submit button selector')
```

**Comment by vgesteljasper** [comment]
Ok, so a gave your example a go but it doesn't want to work. The response I'm getting is some errors of a missing dependencies and the login page as html
eg: `Window.onerror:  Error: rome depends on moment.js, you can get it at http://momentjs.com, or you could use the bundled distribution file instead`
I figure this is because it is not run in a browser envirement.

Although the .login method of osmosis works fine on any other site i tried it on.
Maybe it just can't be done on the website i want it to work on.

**Comment by aragar** [comment]
I haven't try it, but can't you fill your elements in the `.then()` body and use `.click()` after that ?

**Comment by vgesteljasper** [comment]
I just tried but that doesn't seem to work either. I'll close this issue for now as I'm pretty sure this is not related to osmosis but rather to the website i'm trying to login to.
