### ISSUE TITLE
:not() selector - omit child

### ISSUE THREAD

**Issue by scottx** [rchipka/node-osmosis#146]
Hi,

> This might not be an issue but I have already went through the documentation on Sizzle and Slick and googled for someone with the same problem and got no luck. Perhaps here I'll find someone who can help me.

I'm trying to scrape prices on a website for a small project.

In this [scenario](https://www.continente.pt/stores/continente/pt-pt/public/Pages/category.aspx?cat=Lactic%C3%ADnio(eCsf_WebProductCatalog_MegastoreContinenteOnline_Continente_EUR_Colombo_PT)) they have a div.containerPrice which has another div.priceFirstRow containing the price.
It also contains a span with extra information that I don't want.

I tried selecting with the following line, but in this case I won't get the price, because span is there.
**'.containerPrice .priceFirstRow :not("span")'**
I'd like to get the content of .priceFirstRow without the span.

Is this possible?

Thank you
RS

**Comment by rchipka** [comment]
You need to remove the quotes inside of `:not()`.

Any of these should work:

 * `.containerPrice .priceFirstRow :not(span)`
 * `.containerPrice .priceFirstRow > text()`
 * `.containerPrice .priceFirstRow > :first-child`

**Comment by scottx** [comment]
Thank you so much @rchipka
`.containerPrice .priceFirstRow > text()` worked, makes sense.
The others aren't working, I tried span without the double quotes too.
Anyway, it's working with text() and I truly appreciate your help :)
Kindest regards,
RS
