### ISSUE TITLE
Getting src of image

### ISSUE THREAD

**Issue by OmarKan** [rchipka/node-osmosis#165]
I have the following code: 

```javascript
        osmosis
        .get('https://www.amazon.com/AmazonBasics-Apple-Certified-Lightning-Cable/dp/B010S9N6OO/ref=sr_1_1?s=pc&srs=10112675011&ie=UTF8&qid=1496243900&sr=1-1')
        .set({
            image: "#landingImage@src"
        })
        .data(function(listing) {
            // do something with listing data
            console.log("Data");
            console.log(listing);
        })
        .error(console.log)
        .debug(console.log)
```

In the "data" object, the image key must have the url of the image, however, it's returning the base64 representation of the image. 
How can I get the source URL of the image?

**Comment by NegativeIQ** [comment]
Try
`#landingImage@href`

**Comment by OmarKan** [comment]
@NegativeIQ That doesn't work. @src should work fine because the required img tag actually has an attribute called "src" with the url.

**Comment by NegativeIQ** [comment]
No idea, as far as i remember i had never these problem and i was crawling wallpapers website once.

**Comment by rchipka** [comment]
When scraping a site always use *view source* to view the raw HTTP response.

The source code available in the developer tools web inspector will show the live DOM structure and not the original HTML source code.

If you view the original source code, you'll see that `src` attribute is in fact a base64 encoded data-URI.

You'll also see that the `data-old-hires` attribute contains the actual image source.

So, the selector you need is:

`#landingImage@data-old-hires`
