### ISSUE TITLE
How to limit number of item to follow

### ISSUE THREAD

**Issue by sbui2** [rchipka/node-osmosis#174]
hi there,
I have a question. As i have steps below, after complete step 3, i have 10 links to follow in step 4. I just want to follow some of them, let's say 3 of 10. how can i do that? Thanks.
1 osmosis
2    .get('www.abc.com')
3    .find('nav.main-nav-wrap > ul > li > a') // Access to Main menu
4    .follow('@href')

**Comment by aragar** [comment]
Have you tried
```
osmosis
  .get('www.abv.com')
  .config('follow', 3)
```
?

By default, follow is set to 3.

**Comment by aragar** [comment]
As far as I see, currently ```follow``` follows all of the links. You need to write something custom.

**Comment by samogot** [comment]
Use `:lt(3)` selector in step 3
