### ISSUE TITLE
is there an optional find() ?

### ISSUE THREAD

**Issue by elimau** [rchipka/node-osmosis#185]
I have an optional field I need to find. But it will not always be there and using find(), it fails with `(find)no results for "p:nth-of-type(12)"`. Is there a way the `find`optionally?

**Comment by raynoppe** [comment]
I have the same issue. Would be nice to just proceed when not found and log the error.

**Comment by rchipka** [comment]
[.do()](https://rchipka.github.io/node-osmosis/Command.html#do__anchor) can allow you to do this

```javascript
osmosis
...
.do(
  osmosis.find(),
  osmosis.find(),
  ...
)
