### ISSUE TITLE
How to pass the value of the header of an external variable

### ISSUE THREAD

**Issue by volandr** [rchipka/node-osmosis#192]
Tell me please how can I pass the text, for example h1 to the external variable and then use this text from the variable? I understand that this is a stupid question, but it is very important for me.

**Comment by rchipka** [comment]
```javascript
osmosis
...
.set({
  'heading': 'h1'
})
.data(function (data) {
  console.log(data.heading);
});

**Comment by volandr** [comment]
And how to use this "heading" outside osmosis?
For example, how to write "heading" in var head =?
