### ISSUE TITLE
array process

### ISSUE THREAD

**Issue by gen4sp** [rchipka/node-osmosis#202]
```
.set({
          name: 'td[2] > a',
          links: ['td[3] > a@href'],
```
returns `{name:'name', links:['a','b','c']}`

but 
```
.set({
          name: 'td[2] > a',
          links: [{
               url: 'td[3] > a@href',
               type: 'td[3] > a@class',
      }],
```
returns `{name:'name', links:[{url:'a', type:'type'}]}` (only first element, not whole array).
Bug or I am doing something wrong?

**Comment by rchipka** [comment]
```javascript
links: osmosis.find('td[3] > a').set({
  url: '@href',
  type: '@class'
})
```

or, if you need to ensure an array:

```javascript
links: [osmosis.find('td[3] > a').set({
  url: '@href',
  type: '@class'
})]
```

**Comment by rchipka** [comment]
Some explanation:

Wrapping something in an array will ensure that an array is output and will also allow a string selector to return multiple results.

```javascript
links: [{
  url: 'td[3] > a@href',
  type: 'td[3] > a@class',

  // notice that there is no way there could be more than one object ({ ... })
  // what selector would specify when to replicate the object? first one? second? both?
  // keeping this structure, we could (at best) wrap each string selector in an array and get multiple results for those
}]
```

If this clears things up please consider contributing to the wiki, source code docs, or write a tutorial blog post.

**Comment by gen4sp** [comment]
great, thanks
There is a lack of docs and examples (
