### ISSUE TITLE
How selector paginate work?

### ISSUE THREAD

**Issue by keslo** [rchipka/node-osmosis#247]
Hello!

When I insert in `.paginate` selector that match all pagination links (1,2,3...) then I get a follow on only the one link (1). 

Method paginate may work with array of pagination links that I get via selector or I need to set only selector for link “next/previous?

Thanks )

**Comment by NegativeIQ** [comment]
To be honest im not sure, i didnt use osmosis for a quite some time but if i remember correctly you need next page link.

**Comment by rchipka** [comment]
@keslo when passing a selector to `.paginate`, the selector should be able to match to the single next following page link on each loaded page.

Please see the [.paginate tests](https://github.com/rchipka/node-osmosis/blob/master/test/paginate.js#L7) for more details.

**Comment by keslo** [comment]
> @keslo when passing a selector to `.paginate`, the selector should be able to match to the single next following page link on each loaded page.
> 
> Please see the [.paginate tests](https://github.com/rchipka/node-osmosis/blob/master/test/paginate.js#L7) for more details.

There isn’t next following page link on the page. What I may do in this case?

**Comment by rchipka** [comment]
There's no distinction in the layout between the currently selected page and the rest of the page links? Perhaps something like `<a class="current">`, from which you can select the following `<a>` element.

**Comment by keslo** [comment]
> There's no distinction in the layout between the currently selected page and the rest of the page links? Perhaps something like `<a class="current">`, from which you can select the following `<a>` element.

In your case current link from list of links choices automatically?

**Comment by rchipka** [comment]
@keslo I'm not sure what you mean. Please post the HTML layout of the pagination you're working with and I can provide more information.

**Comment by keslo** [comment]
> @keslo I'm not sure what you mean. Please post the HTML layout of the pagination you're working with and I can provide more information.

This is simple example:
`
<table>
<tbody><tr>
	<td>
	<h1 itemprop="name">This title</h1>
	Pages
	<a href="/abc.html?=0">1</a>
	<a href="/abc.html?=1">2</a>
	<a href="/abc.html?=2">3</a>
	<a href="/abc.html?=3">4</a>
<table>
<tbody><tr>
	<td>ID</td>
	<td>Title item</td>
	<td>Price item</td>
</tr>
</tbody></table>
`

**Comment by rchipka** [comment]
@keslo If there's nothing indicating the current, previous, or next page links, then we have nothing to give to `.paginate`.

In fact, if we have every page link listed ahead of time, there's no reason to use `.paginate` at all.

We could simply use `.follow` to follow each of the links listed in pagination.

You could also add `:skip(1)` to the end of your selector like this: `.follow('link-selector-goes-here:skip(1)')` in order to avoid visiting the first page of results twice.
