### ISSUE TITLE
Issues with libxmljs under osmosis installer

### ISSUE THREAD

**Issue by DragoshDX** [rchipka/node-osmosis#73]
Hello. 

I'm trying to install osmosis but the compiler fails when trying to install libxmljs 0.17.1 
I am able to correctly install the 0.16.1 version. This looks like it's an issue in libxmljs rather than osmosis, is there a possibility to specify what version of libxmljs to install? Or anything else I an do in order to get it up and running? 

Thank you,
Dragos.

**Comment by rc0x03** [comment]
The version of libxmljs is defined in the dependency `libxmljs-dom`. You should be able to change it there.

**Comment by DragoshDX** [comment]
Hello. 

I tried getting the code from this repo, without going through NPM but it just doesn't seem to work correctly. 

When doing npm install osmosis 
I get: 

`     Creating library D:\osmosis\node_modules\libxmljs\build\Release\xmljs.lib
  and object D:\osmosis\node_modules\libxmljs\build\Release\xmljs.exp
libxml.lib(parser.obj) : error LNK2001: unresolved external symbol snprintf [D:
\osmosis\node_modules\libxmljs\build\xmljs.vcxproj]
D:\osmosis\node_modules\libxmljs\build\Release\xmljs.node : fatal error LNK1120
: 1 unresolved externals [D:\osmosis\node_modules\libxmljs\build\xmljs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fai
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proce
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\node
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\osmosis\node_modules\libxmljs
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
D:\osmosis
`-- needle@1.0.0
  +-- debug@2.2.0
  | `-- ms@0.7.1
  `-- iconv-lite@0.4.13

npm WARN enoent ENOENT: no such file or directory, open 'D:\osmosis\package.jso
'
npm WARN osmosis No description
npm WARN osmosis No repository field.
npm WARN osmosis No README data
npm WARN osmosis No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\
node_modules\\npm\\bin\\npm-cli.js" "install" "osmosis"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.17.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.17.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\osmosis\npm-debug.log`

I understand the error is in libxmljs, but how can install osmosis without it, perhaps the dependency should be downgraded until they fix that issue?

Thank you.

**Comment by 00kenshin** [comment]
@DragoshDX 

This is a node/gyp/windows issue, i have encountered it before. Have you installed [Microsoft Build Tools](https://www.microsoft.com/en-us/download/details.aspx?id=48159) that usually helps, also running a Admin CMD.

**Comment by DragoshDX** [comment]
Thank you for the info. 

For now I will stick to that Chrome scraping module and perhaps try again on a different machine.
