### ISSUE TITLE
Enhancement - Paginate based of a url

### ISSUE THREAD

**Issue by ahmetabdi** [rchipka/node-osmosis#75]
Instead of doing .get five times for five different pages it would be good if the .paginate selector could take a url structure and add +1 to it e.g... /page/1 , /page/2, /page/3 helpful for sites which have no selector.

When it reaches the paginate limit it could then have a selector to check if it's a 404/500 error or check response status codes

**Comment by rchipka** [comment]
This has been implemented by `.paginate`.
