### ISSUE TITLE
Cookies are not carried forward during pagination

### ISSUE THREAD

**Issue by aner-perez** [rchipka/node-osmosis#76]
I have been trying to figure out the correct way to handle pages which require a form login before accessing other pages on the site.  Initially I tried a `post()` to the form login url and then chaining other `post()`s after this one but the session cookies were not included in subsequent `post()` calls causing all subsequent requests to be redirected to the login page.

I then switched my approach and manually set the cookies by calling `osmosis.config(...)` as follows

```
osmosis
    .post(loginURL, loginData)
    .then(function(context, data) { 
        osmosis.config('headers', { 'cookie': context.request.headers['cookie'] });
        osmosis
            .post(searchURL, searchParams)
            .paginate(nextLinkSelector)
            .find(dataRowSelector)
            .set({ ... })
            .data(function(data) { ... });
     })
```

This works for the first search results page but the next page loaded by `paginate()` is being redirected to the login page which indicates that the cookies are not being carried forward.

Is there a different approach that I should be using to carry cookies forward for all requests?  Do I need to handle all the pages with `then()` instead so I can manually set the cookies for every page instead of using the `paginate()` feature?

**Comment by rc0x03** [comment]
Thanks for reporting this issue. Unforunately, I won't have time to look deeply into this until torrow night. Looks like there could be an issue with pagination cloning document.cookies to the request method.

**Comment by jkrehm** [comment]
I just ran into this issue, too. I spent some time looking at the code to see if I could figure things out, but no dice.

**Comment by rchipka** [comment]
Will reopen if the problem still exists in the latest version.

**Comment by jkrehm** [comment]
This seems to be working for me. Thanks!
