### ISSUE TITLE
*SOS* Cookies failing

### ISSUE THREAD

**Issue by 00kenshin** [rchipka/node-osmosis#77]
Hey, 

I am in desperate need of assistance on this one. I did do my best to read through everything however i cant seem to get it going...

I am acquiring cookie data on demand which returns a string,
ex. 

`"_session=dfjsayojf9232jfsa; waffles=lolololol" etc..`

I am parsing said string into array and object variants, 

ex. 

`["_session=dfjsayojf9232jfsa", "waffles=lolololol"]`

ex. 

```
{
_session:dfjsayojf9232jfsa,
waffles:lolololol
}
```

```

    var cookieObject = await getCookieO();
    var cookieString = await getCookieS();
    var cookieArray = await getCookieA();
```

So far so good the cookie data is valid. Now i have tried all of these variants in

```
osmosis
.config("cookies", cookieObject)
.get("http://www.test.com")
```

And

```
var requestOptions = {
        cookies: cookieArray, // i tred all three in all of them
        headers: {
          'Cookie': cookieObject,

        }
}

osmosis
.get('www.test.com',null, requestOptions)
```

And even the

```
osmosis.headers(requestOptions)
osmosis.config("cookies", cookieObject)
```

methods. Unfortunately i get the "verify page" which is cloudflare btw.

I'm sure I'm doing something wrong. I do like this library but the documentation could use some tlc. 

Thanks guys any help is greatly appreciated,

-kenshin

**Comment by rc0x03** [comment]
Thanks for reporting this, unfortunately I won't be able to look into this until tomorrow night. My advice for now is to verify that cookies are being set using `.then` and `doc.request.headers`. If they are, the issue may be some kind of browser detection that cloud flare has implemented. Thanks for your patience.

**Comment by 00kenshin** [comment]
@rc0x03,
 
>  My advice for now is to verify that cookies are being set using .then and doc.request.headers.

So i went ahead and did that, the data was set as far as i can see. After a bit of investigation i went ahead and tried a different request module namely [got](https://www.npmjs.com/package/got) with the same data and Success!!! 

I believe the problem is either with needle or the pipeline to 
`var req = needle.request(method, href, params, opts, function(err, res, data) {...}`

Perhaps replace needle with got or add a bypass for html data, ideally the former or getting needle to work but i'm not that familiar enough with this package yet to do that.

Thanks, sorry i couldn't be of more help~

-kenshin

**Comment by rchipka** [comment]
Will reopen if this error is verified in the latest version.

**Comment by bitsprint** [comment]
Hi,

I'm struggling with this as well. I'm using the final example above to set the headers and the cookies. It seems to log me in ok, I then set the cookies and headers in config but subsequent requests seem to fail authentication and I then get redirected back to the login page:

```
var osmosis = require('osmosis');

osmosis.get('www.--------.com/login')
       .submit('#MemberLoginForm', { 'data[Member][username]': '--------@gmail.com', 'data[Member][password]': '--------', 'data[Member][return]': '/directory/favorites' })
       .then(function (context, data) {
          osmosis.config('cookies', context.cookies);
          osmosis.headers(context.request.headers);
       })
       .find('div.directory-mysearches > div:nth-child(2) > ul > li > a:nth-child(2)')
       .follow('@href')
       .log(console.log)
       .debug(console.log)
       .error(console.log);
```

This is the log output:

> Debugger listening on port 5858
Server listening on port 80
(get) [redirect] http://www.--------.com/login -> https://www.--------.com/login?
(get) loaded [get] https://www.--------.com/login?
(get) [redirect] https://www.--------.com/login -> https://www.--------.com/directory/favorites
(submit) loaded [post] https://www.--------.com/directory/favorites {"_method":"POST","data[Member][retur":"%2Fdashboard","data[Member][username]":"--------@gmail.com","data[Member][password]":"--------","data[Member][return]":"/directory/favorites"}
(find) found 21 results for "div.directory-mysearches > div:nth-child(2) > ul > li > a:nth-child(2)"
(follow) url: /directory/05fc290a76fd65faa50b9259b76149934dd96de6
(follow) url: /directory/cddf0f49e9f3a9112921c5181ea056467b331965
(follow) url: /directory/fe180e8106fcc8e5a4779212b6bb9d8cab75bfb8
(follow) url: /directory/9b49bad3b0d9836311667e20fd2ce414c7e4d75a
(follow) url: /directory/53c8adc406fad4ed3e27b71d8430273ae17f610b
(follow) url: /directory/8a4edffefda0be11a9b592f4021f2ae46ea97087
(follow) url: /directory/3bc8a286fc935ed97e8f6cf7f14355d6b00b8dda
(follow) url: /directory/bc457e0d1fbcbb619c501396d719f1e770e97e47
(follow) url: /directory/37e5cb21ad5414b67445c7e53e929490e3f8a8b2
(follow) url: /directory/b46027aca1920a2c633e05e4af949145ad6ee934
(follow) url: /directory/d4f8fb44a1efe75c256e8de1017477822e488901
(get) stack: 20, requests: 7 (5 queued), RAM: 41.18Mb (+41.18Mb), libxml: 2.4% (7k nodes), heap: 56% of 18.96Mb
(follow) url: /directory/1a57e7fa2d30973ba299cc90b2ae4c9f93d5d3fc
(follow) url: /directory/7ccfc200187bfca7b31375882f76d29a66c86801
(follow) url: /directory/29b8a765bc09ee014f74b67a710a195aa3fe13e1
(follow) url: /directory/bf315d8d34c277dc87592d3eb9af482b3c63e400
(follow) url: /directory/128b82193c36f89722338dd41a0ffb68266653d4
(follow) url: /directory/efdab3da5fadb339439255c61a35f31e314d9d7e
(follow) url: /directory/0237e70c2cddea2090946dabc783cc7940c0c0db
(follow) url: /directory/29354bd40bdce17789215765a5a68469fca76848
(follow) url: /directory/2d25f709f559ab6cce23f793e5c3dbc8fde944ae
(follow) url: /directory/f191c4364f541a73dd90dc2366d3cc8e2ea6d728
(get) [redirect] https://www.--------.com/directory/05fc290a76fd65faa50b9259b76149934dd96de6 -> https://www.--------.com/login?return=/directory/05fc290a76fd65faa50b9259b76149934dd96de6
(get) [redirect] https://www.--------.com/directory/fe180e8106fcc8e5a4779212b6bb9d8cab75bfb8 -> https://www.--------.com/login?return=/directory/fe180e8106fcc8e5a4779212b6bb9d8cab75bfb8
(get) [redirect] https://www.--------.com/directory/cddf0f49e9f3a9112921c5181ea056467b331965 -> https://www.--------.com/login?return=/directory/cddf0f49e9f3a9112921c5181ea056467b331965
(get) [redirect] https://www.--------.com/directory/9b49bad3b0d9836311667e20fd2ce414c7e4d75a -> https://www.--------.com/login?return=/directory/9b49bad3b0d9836311667e20fd2ce414c7e4d75a
(get) [redirect] https://www.--------.com/directory/53c8adc406fad4ed3e27b71d8430273ae17f610b -> https://www.--------.com/login?return=/directory/53c8adc406fad4ed3e27b71d8430273ae17f610b
(follow) loaded [get] https://www.--------.com/login?return=/directory/cddf0f49e9f3a9112921c5181ea056467b331965
(follow) loaded [get] https://www.--------.com/login?return=/directory/fe180e8106fcc8e5a4779212b6bb9d8cab75bfb8
(follow) loaded [get] https://www.--------.com/login?return=/directory/9b49bad3b0d9836311667e20fd2ce414c7e4d75a
(follow) loaded [get] https://www.--------.com/login?return=/directory/53c8adc406fad4ed3e27b71d8430273ae17f610b
(follow) loaded [get] https://www.--------.com/login?return=/directory/05fc290a76fd65faa50b9259b76149934dd96de6
(get) stack: 21, requests: 12 (5 queued), RAM: 47.80Mb (+6.63Mb), libxml: 4.7% (12k nodes), heap: 82% of 15.09Mb
(get) [redirect] https://www.--------.com/directory/f191c4364f541a73dd90dc2366d3cc8e2ea6d728 -> https://www.--------.com/login?return=/directory/f191c4364f541a73dd90dc2366d3cc8e2ea6d728
(get) [redirect] https://www.--------.com/directory/0237e70c2cddea2090946dabc783cc7940c0c0db -> https://www.--------.com/login?return=/directory/0237e70c2cddea2090946dabc783cc7940c0c0db
(get) [redirect] https://www.--------.com/directory/2d25f709f559ab6cce23f793e5c3dbc8fde944ae -> https://www.--------.com/login?return=/directory/2d25f709f559ab6cce23f793e5c3dbc8fde944ae
(get) [redirect] https://www.--------.com/directory/29354bd40bdce17789215765a5a68469fca76848 -> https://www.--------.com/login?return=/directory/29354bd40bdce17789215765a5a68469fca76848
(get) [redirect] https://www.--------.com/directory/efdab3da5fadb339439255c61a35f31e314d9d7e -> https://www.--------.com/login?return=/directory/efdab3da5fadb339439255c61a35f31e314d9d7e
(follow) loaded [get] https://www.--------.com/login?return=/directory/0237e70c2cddea2090946dabc783cc7940c0c0db
(follow) loaded [get] https://www.--------.com/login?return=/directory/f191c4364f541a73dd90dc2366d3cc8e2ea6d728
(follow) loaded [get] https://www.--------.com/login?return=/directory/29354bd40bdce17789215765a5a68469fca76848
(follow) loaded [get] https://www.--------.com/login?return=/directory/2d25f709f559ab6cce23f793e5c3dbc8fde944ae
(follow) loaded [get] https://www.--------.com/login?return=/directory/efdab3da5fadb339439255c61a35f31e314d9d7e
(get) [redirect] https://www.--------.com/directory/bf315d8d34c277dc87592d3eb9af482b3c63e400 -> https://www.--------.com/login?return=/directory/bf315d8d34c277dc87592d3eb9af482b3c63e400
(get) [redirect] https://www.--------.com/directory/128b82193c36f89722338dd41a0ffb68266653d4 -> https://www.--------.com/login?return=/directory/128b82193c36f89722338dd41a0ffb68266653d4
(get) [redirect] https://www.--------.com/directory/7ccfc200187bfca7b31375882f76d29a66c86801 -> https://www.--------.com/login?return=/directory/7ccfc200187bfca7b31375882f76d29a66c86801
(get) [redirect] https://www.--------.com/directory/29b8a765bc09ee014f74b67a710a195aa3fe13e1 -> https://www.--------.com/login?return=/directory/29b8a765bc09ee014f74b67a710a195aa3fe13e1
(get) [redirect] https://www.--------.com/directory/1a57e7fa2d30973ba299cc90b2ae4c9f93d5d3fc -> https://www.--------.com/login?return=/directory/1a57e7fa2d30973ba299cc90b2ae4c9f93d5d3fc
(follow) loaded [get] https://www.--------.com/login?return=/directory/bf315d8d34c277dc87592d3eb9af482b3c63e400
(follow) loaded [get] https://www.--------.com/login?return=/directory/128b82193c36f89722338dd41a0ffb68266653d4
(follow) loaded [get] https://www.--------.com/login?return=/directory/7ccfc200187bfca7b31375882f76d29a66c86801
(follow) loaded [get] https://www.--------.com/login?return=/directory/1a57e7fa2d30973ba299cc90b2ae4c9f93d5d3fc
(get) stack: 12, requests: 21 (5 queued), RAM: 54.42Mb (+6.62Mb), libxml: 8.3% (22k nodes), heap: 58% of 26.84Mb
(follow) loaded [get] https://www.--------.com/login?return=/directory/29b8a765bc09ee014f74b67a710a195aa3fe13e1
(get) [redirect] https://www.--------.com/directory/d4f8fb44a1efe75c256e8de1017477822e488901 -> https://www.--------.com/login?return=/directory/d4f8fb44a1efe75c256e8de1017477822e488901
(get) [redirect] https://www.--------.com/directory/b46027aca1920a2c633e05e4af949145ad6ee934 -> https://www.--------.com/login?return=/directory/b46027aca1920a2c633e05e4af949145ad6ee934
(get) [redirect] https://www.--------.com/directory/37e5cb21ad5414b67445c7e53e929490e3f8a8b2 -> https://www.--------.com/login?return=/directory/37e5cb21ad5414b67445c7e53e929490e3f8a8b2
(get) [redirect] https://www.--------.com/directory/bc457e0d1fbcbb619c501396d719f1e770e97e47 -> https://www.--------.com/login?return=/directory/bc457e0d1fbcbb619c501396d719f1e770e97e47
(get) [redirect] https://www.--------.com/directory/3bc8a286fc935ed97e8f6cf7f14355d6b00b8dda -> https://www.--------.com/login?return=/directory/3bc8a286fc935ed97e8f6cf7f14355d6b00b8dda
(follow) loaded [get] https://www.--------.com/login?return=/directory/b46027aca1920a2c633e05e4af949145ad6ee934
(follow) loaded [get] https://www.--------.com/login?return=/directory/d4f8fb44a1efe75c256e8de1017477822e488901
(follow) loaded [get] https://www.--------.com/login?return=/directory/37e5cb21ad5414b67445c7e53e929490e3f8a8b2
(follow) loaded [get] https://www.--------.com/login?return=/directory/bc457e0d1fbcbb619c501396d719f1e770e97e47
(follow) loaded [get] https://www.--------.com/login?return=/directory/3bc8a286fc935ed97e8f6cf7f14355d6b00b8dda
(get) [redirect] https://www.--------.com/directory/8a4edffefda0be11a9b592f4021f2ae46ea97087 -> https://www.--------.com/login?return=/directory/8a4edffefda0be11a9b592f4021f2ae46ea97087
(follow) loaded [get] https://www.--------.com/login?return=/directory/8a4edffefda0be11a9b592f4021f2ae46ea97087
(get) stack: 0, requests: 23 (0 queued), RAM: 58.95Mb (+4.52Mb), libxml: 7.6% (22k nodes), heap: 62% of 27.82Mb
