### ISSUE TITLE
:html and :source both resulting in outer html

### ISSUE THREAD

**Issue by deathg0d** [rchipka/node-osmosis#80]
I am trying to get inner html of an element but both :html and :source are giving me outer html. Following is an example demonstrating this.
https://tonicdev.com/56e6c34e101fca12006c7162/56ebf9254085621200c8927f

**Comment by rchipka** [comment]
Thanks, this will be fixed in the next release.

**Comment by deathg0d** [comment]
@rchipka thanks for the quick response, any tentative timeframe on the next npm release?

**Comment by rchipka** [comment]
Fixed in v1.0.0
