### ISSUE TITLE
hrefs with relative path are not resolved

### ISSUE THREAD

**Issue by afm-sayem** [rchipka/node-osmosis#82]
If an anchor tag contains a relative path, it's not resolved according to the current path of the page.

The page in question: http://www.daily-sun.com/printversion
I'm extracting the links of all the categories using this xpath: ```//div[@class='span8']//h3/a```

One sample anchor looks like this: ```<a href="./printversion/type/front-page" class="colorprint1">Front Page</a>```

When I call `follow` on them, in console I'm seeing it's trying to follow: ```http://www.daily-sun.com/printversion/printversion/type/front-page``` whereas it should be ```http://www.daily-sun.com/printversion/type/front-page```

In console, I'm getting
```(follow) [get] http://www.daily-sun.com/printversion/printversion/type/front-page - socket hang up, trying again```

**Comment by rchipka** [comment]
Working with v1.0.0
