### ISSUE TITLE
Trying to split up response data.

### ISSUE THREAD

**Issue by stursby** [rchipka/node-osmosis#83]
Is there a way to run JavaScript on the result and then set multiple values back?

I made a little demo [here](http://code.runnable.com/VyJd9MiLtcIp2Jb-/osmosis-demo-for-node-js).

Thanks!

**Comment by rchipka** [comment]
I believe this is what you're looking for:

osmosis
  .get('https://github.com/stursby')
  .find('title')
  .set('title')
  .then(function(context, data, next) {
    var space = data.title.indexOf(' ');

    data.username = data.title.substring(0, space);
    data.full_name = data.title.substring(space+2, data.title.indexOf(')'));

    next(context, data);
  })
  .data(console.log)

On Apr 28, 2016, at 3:31 PM, charlie hield <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a way to run JavaScript on the result and then set multiple values back?

I made a little demo here<http://code.runnable.com/VyJd9MiLtcIp2Jb-/osmosis-demo-for-node-js>.

Thanks!

**Comment by stursby** [comment]
Awesome! Yes, this is exactly what I was looking for. I notice it then returns all three keys `full_name`, `username`, and `title`. Is there a way to discard `title`? I basically just need it for splitting up, but only want to finish with two.

**Comment by stursby** [comment]
Figured it out... can just delete the key from the data obj. Example:

```js
osmosis
  .get('https://github.com/stursby')
  .find('title')
  .set('title')
  .then(function(context, data, next) {
    var space = data.title.indexOf(' ');

    data.username = data.title.substring(0, space);
    data.full_name = data.title.substring(space+2, data.title.indexOf(')'));
    delete data['title']

    next(context, data);
  })
  .data(console.log)
```
