### ISSUE TITLE
Cant install on Windows 10

### ISSUE THREAD

**Issue by leoxy520** [rchipka/node-osmosis#85]
Libxmljs problem. Can't install on Win 10.

**Comment by JouzaLoL** [comment]
Same. libxmljs cannot be loaded, Dll load error. Win 10 x64 node 6

**Comment by mikowiec** [comment]
libxmljs@0.16 installed OK, without issues, but
   osmosis required libxmljs@0.18

**Comment by skezo** [comment]
Had same issue. Resolved by:

1. Installing Python 2.7.10 - then adding it to Path environment variable
1. Installing Visual Studio 2015 - then adding the environment variable GYP_MSVS_VERSION=2015
1. Quitting the terminal / console if still open
1. reinstall `npm install osmosis`

**Comment by Ivanca** [comment]
Related... https://github.com/rchipka/node-osmosis/issues/60#issuecomment-243279775

**Comment by daniellillja** [comment]
I was just able to install this by:

1. Forcing it to use Python 2.7 by removing by the my Python3 directory and adding `C:\Python27` to my PATH (fixes Python version error)
2. Running `npm install --global --production windows-build-tools` (fixed Visual Studio build tools error)

**Comment by rchipka** [comment]
This is a libxmljs issue and should be reported there.
