### ISSUE TITLE
Collect the results

### ISSUE THREAD

**Issue by bisubus** [rchipka/node-osmosis#91]
Is Osmosis supposed to collect the results after the job is done? Is there already a command that could handle this? 

I would expect some methods to group/concatenate the results into array, like it is done in RxJS. 

I was hoping that `done` got the results (so it could be promisified), but it it looks like it is just being called with no params.

**Comment by rchipka** [comment]
You can do this using nested `.set` calls.

osmosis.get('example.com')
.set([
    osmosis
        .find("#results > .result")
        .set({
            title: 'h2',
            description: 'p'
        })
])
.data(function(array) {
    // array of results
})

**Comment by bisubus** [comment]
@rchipka Thanks, simple and brilliant, [wiki example](https://github.com/rchipka/node-osmosis/wiki#set) started to make more sense to me in this context. I've tried something like

```
Command.prototype.collect = function () {
	let results = [];

	return this.then((ctx, data, next, done) => {
		results.push(data);

		if (ctx.last) {
			next(ctx, results);
			done();
		}
	});
}
```
and it worked, but idiomatic approach feels more natural.
