### ISSUE TITLE
Variable URL and query string

### ISSUE THREAD

**Issue by bisubus** [rchipka/node-osmosis#94]
Currently it is possible to make URL variable with

```
osmosis.post((ctx, data) => data.url)
```

Can the same thing be done for query strings?

It looks like callback function for query string [was planned](https://github.com/rchipka/node-osmosis/blob/1.0.1/lib/commands/get.js#L73) but is not there yet.

It would be convenient to have an option to have common callback for both URL and query if they are determined by common logic. This way the first `callback` argument of `get`/`post` may return a string or an object:

```
osmosis.post((ctx, data) => ..., 'query')
osmosis.post('url', (ctx, data) => ...)
osmosis.post((ctx, data) => ({ url: .., query: ...}))
```

**Comment by rchipka** [comment]
This is now supported by `get()` and `post()` by providing a function and returning a URL string or context.
