### ISSUE TITLE
Cant install on Windows 7, x86

### ISSUE THREAD

**Issue by mikowiec** [rchipka/node-osmosis#99]
win7-32
node 5.10, node-gyp 3.3

the issue related to libxmljs@0.18, libxmljs@0.17
libxmljs@0.16 installed without problem.

Could you refer to @0.16 ?

**Comment by cohenpts** [comment]
same issue win7 64
node v4.4.0
VS 2013 installed and ENV vars added

**Comment by rchipka** [comment]
This is a libxmljs issue and should be reported there.
